chore: prep market creator for minting
valory-xyz/market-creator pull request #54
Opened 2023-08-21 20:17 UTC by DavidMinarsch

2023-08-22 12:50 UTC, jmoreira-valory commented on mints/mapping.txt
> +X-"skill/valory/market_validation_abci/0.1.0" -> 14, 22
```suggestion
```

2023-08-22 15:00 UTC, jmoreira-valory commented on mints/mapping.txt
> +X-"skill/valory/market_maker_abci/0.1.0" -> 14, 16, 17, 22, 33, "skill/valory/market_creation_manager_abci/0.1.0", "skill/valory/market_validation_abci/0.1.0"
```suggestion
X-"skill/valory/market_maker_abci/0.1.0" -> 14, 16, 17, 22, 33, "skill/valory/market_creation_manager_abci/0.1.0"
```

2023-08-22 15:01 UTC, jmoreira-valory commented on mints/mapping.txt
> +X-"agent/valory/market_maker/0.1.0" -> 1, 2, 3, 4, 5, 6, 7, 39, 57, 8, 9, 10, 11, 18, 19, 20, 12, 5 contracts above, 13, 14, 16, 17, 22, 33, 3 skills abovew
```suggestion
X-"agent/valory/market_maker/0.1.0" -> 1, 2, 3, 4, 5, 6, 7, 39, 57, 8, 9, 10, 11, 18, 19, 20, 12, 5 contracts above, 13, 14, 16, 17, 22, 33, 2 skills above
```

2023-08-22 20:17 UTC, jmoreira-valory requested changes
Please merge main as one component has been removed.

2023-08-24 12:23 UTC, DavidMinarsch commented on mints/02.json
> +{"name":"contract/valory/conditional_tokens:0.1.0","description":"The scaffold contract scaffolds a contract to be implemented by the developer.","code_uri":"ipfs://bafybeihufvbfz7l7fb3fvsalp6jmplkxo
"The scaffold contract scaffolds a contract to be implemented by the developer." -> you need to update the metadata of this package in its yaml @jmoreira-valory

2023-08-24 12:23 UTC, DavidMinarsch commented on mints/03.json
> +{"name":"contract/valory/fpmm_deterministic_factory:0.1.0","description":"The scaffold contract scaffolds a contract to be implemented by the developer.","code_uri":"ipfs://bafybeibveawsp3ir67otkyswy
"The scaffold contract scaffolds a contract to be implemented by the developer." -> you need to update the metadata of this package in its yaml @jmoreira-valory

2023-08-24 12:24 UTC, DavidMinarsch commented on mints/05.json
> +{"name":"contract/valory/wxdai:0.1.0","description":"The scaffold contract scaffolds a contract to be implemented by the developer.","code_uri":"ipfs://bafybeicsbm2itxmmifkkyroozp6dh45aatrqabv6bcpkm7
"The scaffold contract scaffolds a contract to be implemented by the developer." -> you need to update the metadata of this package in its yaml @jmoreira-valory

2023-08-24 12:24 UTC, DavidMinarsch commented on mints/06.json
> +{"name":"contract/valory/fpmm:0.1.0","description":"The scaffold contract scaffolds a contract to be implemented by the developer.","code_uri":"ipfs://bafybeihmzrpamqh654kb2vzzybzkirk75rmxj6rttrbhhkr
"The scaffold contract scaffolds a contract to be implemented by the developer." -> you need to update the metadata of this package in its yaml @jmoreira-valory

2023-08-24 12:24 UTC, DavidMinarsch commented on mints/07.json
> +{"name":"skill/valory/market_creation_manager_abci:0.1.0","description":"The scaffold skill is a scaffold for your own skill implementation.","code_uri":"ipfs://bafybeihhtzwffrfs2owanv627tx53gtaapeel
"The scaffold skill is a scaffold for your own skill implementation." -> you need to update the metadata of this package in its yaml @jmoreira-valory

2023-08-24 12:24 UTC, DavidMinarsch commented on mints/08.json
> +{"name":"skill/valory/market_maker_abci:0.1.0","description":"The scaffold skill is a scaffold for your own skill implementation.","code_uri":"ipfs://bafybeigw7ep2icp3xayuwkkuebw2vzahqfetryyxh5lekjjr
See above

2023-08-25 09:46 UTC, jmoreira-valory approved these changes

2023-08-25 10:19 UTC, merged